Hibernate
ramilgal/JDBC pull request #3
Opened 2023-04-18 06:25 UTC by ramilgal

нужна помощь

2023-04-18 17:42 UTC, OlgaLugacheva requested changes

2023-04-18 17:42 UTC, OlgaLugacheva commented on src/main/java/service/EmployeeDaoImpl.java
> +        printAllEmployees(entityManager);
вызов этого метода тут не нужен как и в других аналогичных методах - нужно удалить.

2023-04-18 17:42 UTC, OlgaLugacheva commented on src/main/java/service/EmployeeDaoImpl.java
> +        entityManager.getTransaction().begin();
тут две разные транзакции работают, удивительно, что это вообще работает - нужно исправить примерно так 
```
  EntityTransaction transaction = entityManager.getTransaction();
        transaction.begin();
-----
transaction.commit();
```

2023-04-18 17:42 UTC, OlgaLugacheva commented on src/main/java/service/EmployeeDaoImpl.java
> +        EntityManager entityManager = entityManagerFactory.createEntityManager();
вот это не нужно создавать в кажлм методе, достаточно создать однажды и использовать

2023-04-19 09:48 UTC, ramilgal commented on src/main/java/service/EmployeeDaoImpl.java
> +        printAllEmployees(entityManager);
не понял, какого именно метода ? какая строка

2023-04-20 18:24 UTC, OlgaLugacheva requested changes

2023-04-20 18:24 UTC, OlgaLugacheva commented on src/main/java/service/EmployeeDaoImpl.java
> +        printAllEmployees(entityManager);
printAllEmployees(entityManager); этого

2023-04-24 07:42 UTC, ramilgal commented on src/main/java/service/EmployeeDaoImpl.java
> +        printAllEmployees(entityManager);
public List<Employee> getAllEmployee() {
        List<Employee> employees = new ArrayList<>();
        entityManager.getTransaction().begin();
        entityManager.getTransaction().commit();
        printAllEmployees(entityManager);
        entityManager.close();
        entityManagerFactory.close();
        return employees;
    }

printAllEmployees(entityManager);   это мне дает вывести всех сотрудников на экран, как не нужен ? а как тогда получить список сотрудников и вывести на экран ??
"
TypedQuery<Employee> query = entityManager.createQuery("from Employee", Employee.class);
        for (Employee printEmployees:query.getResultList()) {
            System.out.println(printEmployees);}
" - вот это я упаковал в метод    -   printAllEmployees(entityManager);   -

2023-05-02 13:31 UTC, merged